### ISSUE TITLE
Gamecrash on Save/Autosave?

### ISSUE THREAD

**Issue by Marcel40625** [tom-90/RROx#17]
Hey there, sometimes i get a Gamecrash on saving, the save is successfull (can load it after restart) but client crashes.

does this have anything todo with RROx?

the thing is it crashed before on manual save and thats why i searched for a tool like RROx.

but maybe someone has an idea

running windows 10pro, AMD 3800x, RTX 3070, 32GB RAM, Game on SSD, Video driver up2date

**Comment by tom-90** [comment]
If the game was crashing on saving before using RROx, then that's probably not a problem I can fix. RROx just runs the game code that saves the game.
