### ISSUE TITLE
Version 1.8.0 Cant activate some switches

### ISSUE THREAD

**Issue by TilTisback** [tom-90/RROx#21]
Hello,
some switches on my map cant be activated with the new update. before it worked perfectly.

When i hover over the switch it wont show the "flip switch" textbox and therefore cant be flipped.

restarting the program and re-attaching it does not work.
deleting the switch and rebuilding it either does not work or sometimes moves the inoperable switch to the next adjacent one.

![2022-01-21 18_54_43-RailroadsOnline Extended](https://user-images.githubusercontent.com/13772017/150576811-c632818b-4fc1-47f8-872f-b48579eef008.png)
![2022-01-21 18_54_30-RailroadsOnline Extended](https://user-images.githubusercontent.com/13772017/150576814-5e7f17c5-c13d-4d7b-a191-b5385d0a99a5.png)
![2022-01-21 18_48_26-RROxOverlay](https://user-images.githubusercontent.com/13772017/150576820-01cc0eb1-bf57-4cec-b126-54b67471aeb0.png)
![2022-01-21 18_48_08-RROxOverlay](https://user-images.githubusercontent.com/13772017/150576821-3c62ce03-2675-45c8-bb7c-9fc49799a824.png)

**Comment by tom-90** [comment]
Can you share your savefile? Then I can test this out

**Comment by TilTisback** [comment]
[slot1.zip](https://github.com/tom-90/RROx/files/7918203/slot1.zip)

here is the savefile.
the switches in question are N/W of the sawmill and N/E of the iron ore mine.
ps: when i tried to flip the switch today it worked again. maybe it needs a restart of my computer to fix? i will report if i encounter the problem again. thanks for your quick reply!

**Comment by tom-90** [comment]
Issue reporting is moving to a new discord server: [https://discord.gg/vPxGPCDFBp](https://discord.gg/vPxGPCDFBp)
