### ISSUE TITLE
Suggestion: Syncing locomotive controls for longer trains

### ISSUE THREAD

**Issue by TilTisback** [tom-90/RROx#22]
Hello, 
since the new physics update, the locomotives really struggle to pull up longer trains up a hill.
Wich brings up the possibility of using two or more locomotives for more power.

In the F1 menu you can already open up multiple control panels to set the regulator and brakes of multiple locos.
My suggestion is to link one or more of these control panels to a master locomotive wich you can control with the F-menu or by 1st person.
The slave controllers would simply copy the regulator/brakes etc. to its respective locomotive.

**Comment by tom-90** [comment]
I was already planning to add this feature. When I have time, I will implement it.

**Comment by tom-90** [comment]
Issue reporting is moving to a new discord server: [https://discord.gg/vPxGPCDFBp](https://discord.gg/vPxGPCDFBp)
