### ISSUE TITLE
will it get me banned in other games?

### ISSUE THREAD

**Issue by mrvice** [tom-90/RROx#6]
Iam a little bit concerned how i would have to use it.

I have installed valorant wich has an low level anti cheat software. (vanguard)

Will i be safe to use RROx or could this get me banned from Valorant

**Comment by tom-90** [comment]
Personally, I do not have experience with ant-cheat software from other games, and have not tested the effect RROx has on it.
Such anti cheat software could detect Cheat Engine (the program RROx relies on), however Cheat Engine is not permanently installed on your system, and is only used while RROx is running.

My guess is that RROx does not get detected, but I can not give guarantees.
If you decide to try RROx, then please share your experience such that others can make a decision.
