### ISSUE TITLE
caboose and loco not rendering in minimap when connected as client

### ISSUE THREAD

**Issue by RagingLightning** [tom-90/RROx#7]
as stated above, usually neither locos nor cabooses (?) render on my client-only minimap, however once I was on teh same train as the host, they showed up,

I don't think, it's purely because of replication distance, because they don't show up, even when I'm right next to them

**Comment by tom-90** [comment]
I will do some more testing. Did this issue occur for all types of locomotives or only for specific ones?

**Comment by RagingLightning** [comment]
I noticed it originally when driving Betsy, so Porter 1 type, I'm pretty sure it also happened sith fhe Climax. When I had the host with me, he was driving a Heisler type, I'll take a closer look at it asap and will report back :)Am 31.12.2021 17:55 schrieb Tom ***@***.***>:
I will do some more testing. Did this issue occur for all types of locomotives or only for specific ones?

**Comment by tom-90** [comment]
This should be fixed in version 1.7.0.
